""""""""""""""""""""""""""
"""" Miscellaneous settings that might be worth enabling

"set cursorline         " highlight current line
"set autoread           " autoreload the file in Vim if it has been changed outside of Vim
set background=dark


" enter the new millienium
set nocompatible

" enable syntax and plugins for newtr
filetype plugin on
syntax enable

" FINDING FILES
set path+=**      " Provides tab-completion  for all file-related tabs
set wildmenu      " Display all matching files when we complete tab

" NOW WE CAN
" - Hit tab to :find by partial match
" - Use * to make it fuzzy

" THINGS TO CONSIDER
" - :b lets you autocomplete any open buffer

" TAG JUMPING

" Create the 'tags' file after ctags is installed
command! MakeTags !ctags -R .


" Now we can:
" - Use ^] to jump to tag under cursor
" - Use g^] for ambiguous tags
" - Use ^t to jump back up the tag stack
" - This doesn't help if you want a visual list of tags

" AUTOCOMPLETE
" The good stuff is documented in |ins-completion|

" - ^x^n for JUST this file
" - ^x^f for filenames (works with our path trick!)
" - ^x^] for tags only
" - ^n for anything specifid by the 'complete' option

" - Use ^n and ^p to go back and forth in the suggestion list!

" SHOWING DOTFILES (NETWR)
let g:netrw_list_hide = '\(^\|\s\s\)\zs\.\S\+'

" Remap keys to navigate better between windows
nnoremap <C-J> <C-W><C-J>
nnoremap <C-K> <C-W><C-K>
nnoremap <C-L> <C-W><C-L>
nnoremap <C-H> <C-W><C-H>

" Shortcuts

" Saving shortcut
nnoremap <C-W> :w <CR>

" Create new split and switch to it.
nnoremap <Leader>w <C-w>v<C-w>l
nnoremap <Leader>s <C-w>s<C-w>j
" Close split
nnoremap <Leader>c <C-w>c

" Easier movement in split windows.
" nnoremap <Leader>h <C-w>h
" nnoremap <Leader>j <C-w>j
" nnoremap <Leader>k <C-w>k
" nnoremap <Leader>l <C-w>l

""""""""""""""""""""""""""
""""""""""""""""""""""""""
""" Plugins

call plug#begin('~/.vim/plugged')


""""""""""""""""""""""""""
""" Currently in use

Plug 'chriskempson/base16-vim'
" Plug 'arcticicestudio/nord-vim', { 'branch': 'develop' }

Plug '~/.fzf'
Plug 'junegunn/fzf.vim'
Plug 'junegunn/goyo.vim'
Plug 'junegunn/limelight.vim'
Plug 'junegunn/vim-easy-align'

Plug 'tpope/vim-sensible'
Plug 'tpope/vim-eunuch'
Plug 'tpope/vim-surround'
Plug 'tpope/vim-fugitive'
Plug 'tpope/vim-markdown'

" Plug 'terryma/vim-multiple-cursors'
Plug 'SirVer/ultisnips'
Plug 'honza/vim-snippets'

Plug 'vim-airline/vim-airline'
Plug 'vim-airline/vim-airline-themes'
Plug 'scrooloose/nerdtree'
Plug 'Xuyuanp/nerdtree-git-plugin'
Plug 'lervag/vimtex'
Plug 'christoomey/vim-tmux-navigator'

Plug 'scrooloose/syntastic'
Plug 'reedes/vim-pencil'
Plug 'tpope/vim-repeat'

""""""""""""""""""""""""""
""" Markdown; figure it out!

autocmd BufRead,BufNewFile {*.markdown,*.mdown,*.mkdn,*.md,*.mkd} set filetype=markdown


Plug 'iamcco/markdown-preview.nvim', { 'do': { -> mkdp#util#install() } }
Plug 'ferrine/md-img-paste.vim'
" Plug 'https://github.com/vim-pandoc/vim-pandoc'
" Plug 'vim-pandoc/vim-pandoc-syntax'

Plug 'godlygeek/tabular'
Plug 'elzr/vim-json'
" Plug 'plasticboy/vim-markdown'
" let g:vim_markdown_folding_disabled = 1
" let g:vim_markdown_conceal = 0
" let g:tex_conceal = ""
" let g:vim_markdown_math = 1
" let g:vim_markdown_frontmatter = 1  " for YAML format
" let g:vim_markdown_toml_frontmatter = 1  " for TOML format
" let g:vim_markdown_json_frontmatter = 1  " for JSON format

""""""""""""""""""""""""""
""" Currently NOT in use

" Plug 'tpope/vim-vinegar'
" Plug 'mbbill/undotree'
" Plug 'flazz/vim-colorschemes'
" Plug 'fatih/vim-go'
" Plug 'vimwiki/vimwiki'


call plug#end()




""""""""""""""""""""""""""
""""""""""""""""""""""""""
""" Basic behavior

set number              " show line numbers
set relativenumber      " show relative numbers!
set wrap                " wrap lines
set encoding=utf-8      " set encoding to UTF-8 (default was "latin1")
set mouse=a             " enable mouse support (might not work well on Mac OS X)
set wildmenu            " visual autocomplete for command menu
set lazyredraw          " redraw screen only when we need to
set showmatch           " highlight matching parentheses / brackets [{()}]
set laststatus=2        " always show statusline (even with only single window)
set ruler               " show line and column number of the cursor on right side of statusline
set visualbell          " blink cursor on error, instead of beeping


""""""""""""""""""""""""""
""" Key bindings

" configure other way to escape, as well as leader key
let mapleader=" "
inoremap jk <esc>

" move vertically by visual line (don't skip wrapped lines)
nmap j gj
nmap k gk


""""""""""""""""""""""""""
"""" Vim Appearance

" put colorscheme files in ~/.vim/colors/
" good colorschemes: murphy, slate, molokai, badwolf, solarized

let base16colorspace=256  " Access colors present in 256 colorspace
colorscheme badwolf " nord badwolf

if filereadable(expand("~/.vimrc_background"))
  let base16colorspace=256
  source ~/.vimrc_background
endif

" use filetype-based syntax highlighting, ftplugins, and indentation
" syntax enable
filetype plugin indent on


""""""""""""""""""""""""""
"""" Tab settings

set tabstop=4           " width that a <TAB> character displays as
set expandtab           " convert <TAB> key-presses to spaces
set shiftwidth=4        " number of spaces to use for each step of (auto)indent
set softtabstop=4       " backspace after pressing <TAB> will remove up to this many spaces

set autoindent          " copy indent from current line when starting a new line
set smartindent         " even better autoindent (e.g. add indent after '{')


""""""""""""""""""""""""""
"""" Search settings

set incsearch           " search as characters are entered
set hlsearch            " highlight matches

" turn off search highlighting with <CR> (carriage-return)
nnoremap <CR> :nohlsearch<CR><CR>




""""""""""""""""""""""""""
""""""""""""""""""""""""""
""" Other behavior

" Tabularize, for LaTeX, with ampersands!
nnoremap <Leader>a :Tabularize /&<CR>
vnoremap <Leader>a :Tabularize /&<CR>


""""""""""""""""""""""""""
" Automatic tabularization, from Tim Pope

inoremap <silent> <Bar>   <Bar><Esc>:call <SID>align()<CR>a
function! s:align()
        let p = '^\s*|\s.*\s|\s*$'
        if exists(':Tabularize') && getline('.') =~# '^\s*|' && (getline(line('.')-1) =~# p || getline(line('.')+1) =~# p)
                let column = strlen(substitute(getline('.')[0:col('.')],'[^|]','','g'))
                let position = strlen(matchstr(getline('.')[0:col('.')],'.*|\s*\zs.*'))
                Tabularize/|/l1
                normal! 0
                call search(repeat('[^|]*|',column).'\s\{-\}'.repeat('.',position),'ce',line('.'))
        endif
endfunction



""""""""""""""""""""""""""
" Markdown Preview

" Don't close preview tab when switching to other buffers
"let g:mkdp_auto_close = 0


""""""""""""""""""""""""""
" fzf
nnoremap <Leader>f :FZF<Enter>

""""""""""""""""""""""""""
" md image paste

autocmd FileType markdown nmap <silent> <leader>p :call mdip#MarkdownClipboardImage()<CR>
" there are some defaults for image directory and image name, you can change them
let g:mdip_imgdir                      = 'image-assets'
" let g:mdip_imgname                   = 'image'

""""""""""""""""""""""""""
" LaTeX

let g:tex_flavor                       = 'latex'
let g:tex_conceal                      = ''
let g:vimtex_fold_manual               = 1
let g:vimtex_latexmk_continuous        = 1
let g:vimtex_compiler_progname         = 'nvr'
" use SumatraPDF if you are on Windows
let g:vimtex_view_method               = 'skim'

"autocmd FileType tex set autoindent
" Set the make program (rubber)
" autocmd FileType tex set makeprg=rubber\ --inplace\ --maxerr\ 1\ \ --pdf\ --short\ --quiet\ --force\ %
" Mappings for compiling Latex file
" autocmd FileType tex nmap <buffer> <C-T> :!latexmk -pdf %<CR>
" autocmd FileType tex nmap <buffer> <C-T> :!rubber --pdf --force --short %<CR>
" autocmd FileType tex nmap <buffer> T :!open -a Skim %<.pdf %<.pdf<CR><CR>
" autocmd FileType tex nmap <buffer> C :!rubber --clean<CR>


"""""""""""""""""""
" NERDtree
nnoremap <Leader>n :NERDTreeToggle<Enter>
let NERDTreeQuitOnOpen = 1

" automatically close if NERDtree is only left standing
autocmd bufenter * if (winnr("$") == 1 && exists("b:NERDTree") && b:NERDTree.isTabTree()) | q | endif

" Turn off auto-insert
augroup auto_comment
    au!
    au FileType * setlocal formatoptions-=c formatoptions-=r formatoptions-=o
augroup END


" Paste problems in vim
" See: https://www.reddit.com/r/neovim/comments/9ufg11/disable_insert_paste_mode/

" Toggle paste mode on and off
map <leader>tt :setlocal paste!<cr>

" Disable paste mode when leaving insert mode
autocmd InsertLeave * set nopaste

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Autocommands
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" Remove trailing whitespace on save.
" autocmd BufWrite * :%s/\s\+$//e

" Skeleton files
autocmd! BufNewFile * silent! 0r ~/.vim/skel/template.%:e

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Snippets
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

let g:UltiSnipsExpandTrigger       = '<tab>'
let g:UltiSnipsJumpForwardTrigger  = '<tab>'
let g:UltiSnipsJumpBackwardTrigger = '<s-tab>'

let g:vimtex_quickfix_mode         = 0
" set conceallevel                   = 1
let g:tex_conceal                  = 'abdmg'

autocmd FileType latex,tex,md,markdown setlocal spell
set spelllang=en_us,en_gb
inoremap <C-l> <c-g>u<Esc>[s1z=`]a<c-g>u

" Set spellfile to location that is guaranteed to exist,
" can be symlinked to Dropbox or kept in Git
" and managed outside of thoughtbot/dotfiles using rcm.
set spellfile=~/roles/dotfiles/vim/vim-spell-en.utf-8.add

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Syntastic
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""

" set statusline+=%#warningmsg"#
" set statusline+=%{SyntasticStatuslineFlag()}
" set statusline+=%*

let g:syntastic_always_populate_loc_list = 1
let g:syntastic_auto_loc_list            = 1
let g:syntastic_check_on_open            = 1
let g:syntastic_check_on_wq              = 0

"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
" Pencil
"""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""""
let g:pencil#wrapModeDefault = 'soft'   " default is 'hard'

augroup pencil
  autocmd!
  autocmd FileType markdown call pencil#init()
  autocmd FileType text     call pencil#init({'wrap': 'hard'})
augroup END

""""""""""""""""""""""""""
" Writing optionS! Goyo, Limelight, and Vim-Pencil

nnoremap <Leader>gg :Goyo<CR>
let g:limelight_conceal_ctermfg = 240
autocmd! User GoyoEnter Limelight
autocmd! User GoyoLeave Limelight!

 " Pencil / Writing Controls {{{
let g:pencil#wrapModeDefault     = 'soft'
let g:pencil#textwidth           = 50
let g:pencil#joinspaces          = 0
let g:pencil#cursorwrap          = 1
let g:pencil#conceallevel        = 2
let g:pencil#concealcursor       = 'c'
let g:pencil#softDetectSample    = 20
let g:pencil#softDetectThreshold = 130
 " }}}
